# generated by datamodel-codegen:
#   filename:  code.json
#   timestamp: 2022-08-17T11:25:04+00:00

from typing import Any, List, Optional

from pydantic import BaseModel


class Detail(BaseModel):
    course: str
    score: float
    met_deadlines: bool


class Week(BaseModel):
    score: float
    details: List[Detail]
    rank: int
    diff: Optional[int] = None


class ModelItem(BaseModel):
    uid: str
    english_name: str
    weeks: List[Week]
    started_at: str
    name: str
    gender: str
    photo: Any
    job: str
    organization: Optional[str]
    enrollment_status: str
    enrollment_granted: bool
    is_new: bool
    is_certification_started: bool
    city: str
    country: str
    diploma_title: Any
    diploma_url: Any
    diploma_score: Any
    diploma_art_director: Any
    diploma_patron: Any
    diploma_designers: Any
    diploma_editors: Any
    diploma_managers: Any


class Model(BaseModel):
    __root__: List[ModelItem]
